In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn.linear_model import LinearRegression

In [3]:
data  = pd.read_csv('topdown_data.csv')

In [20]:
Y = data['time'][0:57]
X = data['temp'][0:57]
Z = data['var'][0:57]
#print(Y)
Y = Y.values.reshape(-1, 1)

In [21]:
#n*2^(len(bit(W)))
X_ = Z
X_ = X_.values.reshape(-1, 1)
ones = np.ones((X_.shape[0], 1))
X_ = np.concatenate((ones, X_), axis = 1)
model = LinearRegression(fit_intercept=False)
model.fit(X_, Y)
print(model.coef_)

[[-3.32804428e+01  5.33949020e-04]]


In [5]:
X_ = Z
f = open("nbit.csv", "w")
X_ =5.33949020e-04*(X_) + -3.32804428e+01
for ii in X_:
  f.write(str(ii))
  f.write('\n')

In [6]:
#log2(x)
X_ = np.log2(X)
X_ = X_.values.reshape(-1, 1)
ones = np.ones((X_.shape[0], 1))
X_ = np.concatenate((ones, X_), axis = 1)
model = LinearRegression(fit_intercept=False)
model.fit(X_, Y)
print(model.coef_)

[[-841.04006535   62.15103496]]


In [7]:
X_ = np.log2(X)
f = open("log.csv", "w")
X_ =62.15103496*(X_) + -841.04006535 
for ii in X_:
  f.write(str(ii))
  f.write('\n')

In [8]:
#sqrt(x)
X_ = np.sqrt(X)
X_ = X_.values.reshape(-1, 1)
ones = np.ones((X_.shape[0], 1))
X_ = np.concatenate((ones, X_), axis = 1)
model = LinearRegression(fit_intercept=False)
model.fit(X_, Y)
print(model.coef_)

[[-119.31451633    0.73302702]]


In [9]:
X_ = np.sqrt(X)
f = open("sqrt.csv", "w")
X_ = 0.73302702*(X_) + -119.31451633
for ii in X_:
  f.write(str(ii))
  f.write('\n')

In [12]:
#x
X_ = X
X_ = X_.values.reshape(-1, 1)
ones = np.ones((X_.shape[0], 1))
X_ = np.concatenate((ones, X_), axis = 1)
model = LinearRegression(fit_intercept=False)
model.fit(X_, Y)
print(model.coef_)

[[-8.39905974e+00  8.26970152e-04]]


In [11]:
X_ = X
f = open("x.csv", "w")
X_ = 8.26970152e-04*(X_) + -8.39905974e+00
for ii in X_:
  f.write(str(ii))
  f.write('\n')

In [12]:
#xlogx
X_ = X * np.log2(X)
X_ = X_.values.reshape(-1, 1)
ones = np.ones((X_.shape[0], 1))
X_ = np.concatenate((ones, X_), axis = 1)
model = LinearRegression(fit_intercept=False)
model.fit(X_, Y)
print(model.coef_)

[[1.46416058e+00 4.24393127e-05]]


In [13]:
X_ = X*np.log2(X)
f = open("xlogx.csv", "w")
X_ = 4.24393127e-05*(X_) + 1.46416058e+00
for ii in X_:
  f.write(str(ii))
  f.write('\n')

In [14]:
#x2
X_ = X * X
X_ = X_.values.reshape(-1, 1)
ones = np.ones((X_.shape[0], 1))
X_ = np.concatenate((ones, X_), axis = 1)
model = LinearRegression(fit_intercept=False)
model.fit(X_, Y)
print(model.coef_)

[[6.94126336e+01 1.14152606e-09]]


In [16]:
X_ = X*X
f = open("x2.csv", "w")
X_ = 1.14152606e-09*(X_) + 6.76555542e+01
for ii in X_:
  f.write(str(ii))
  f.write('\n')

In [16]:
#x3
X_ = X * X * X
X_ = X_.values.reshape(-1, 1)
ones = np.ones((X_.shape[0], 1))
X_ = np.concatenate((ones, X_), axis = 1)
model = LinearRegression(fit_intercept=False)
model.fit(X_, Y)
print(model.coef_)

[[7.78951264e-33 1.95031195e-15]]


In [17]:
X_ = X*X*X
f = open("x3.csv", "w")
X_ =  1.95031195e-15*(X_) + 7.78951264e-33 
for ii in X_:
  f.write(str(ii))
  f.write('\n')

In [23]:
#2^n
X_ = 2**X
print(X_)
X_ = X_.values.reshape(-1, 1)
ones = np.ones((X_.shape[0], 1))
X_ = np.concatenate((ones, X_), axis = 1)
model = LinearRegression(fit_intercept=False)
model.fit(X_, Y)
print(model.coef_)

0     4.149516e+180
1               inf
2               inf
3               inf
4               inf
5               inf
6               inf
7               inf
8               inf
9               inf
10              inf
11              inf
12              inf
13              inf
14              inf
15              inf
16              inf
17              inf
18              inf
19              inf
20              inf
21              inf
22              inf
23              inf
24              inf
25              inf
26              inf
27              inf
28              inf
29              inf
30              inf
31              inf
32              inf
33              inf
34              inf
35              inf
36              inf
37              inf
38              inf
39              inf
40              inf
41              inf
42              inf
43              inf
44              inf
45              inf
46              inf
47              inf
48              inf
49              inf


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [20]:
X_ = 2**X
f = open("2x.csv", "w")
X_ = 0.        *(X_) + 206.62219641
for ii in X_:
  f.write(str(ii))
  f.write('\n')

In [21]:
from decimal import *

In [25]:
#x!
sum = 0
Y = data['time']
f = open("finallll.csv", "w")
for i in range(61):
  #tính bình phương độ lệch giữa mỗi giá trị n! và t(n) tương ứng với n
  x = math.factorial(X[i]) - Y[i]
  x = x*x
  sum =  sum+x
  x = Decimal(x)
  if len(str(x)) > 6:
    x = '{:.5E}'.format(x) 
  f.write(x)
  f.write('\n')
sum = Decimal(sum//61)
#MSE
if len(str(sum)) > 6:
    sum = '{:.5E}'.format(sum) 
print(sum)
f.write(str(sum))

OverflowError: int too large to convert to float

In [ ]:
'''
Cấu hình thử nghiệm gồm:
CPU: I5-9400F
RAM: 16gb
GPU: NVIDIA GeForce GTX 1650
'''